name: release-please

on:
  push:
    branches: [ main ]

permissions: write-all

jobs:
  # Release-please for auto-updated PRs
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: simple  # actual releasing is handled by goreleaser
          package-name: computeblade-agent
          skip-github-release: true  # GH release is created by goreleaser
